name: pharmacyapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth:
  firebase_core:
  cloud_firestore:
  flutter_svg:
  flutter_bloc:
  dartz:
  get_it:
  http: ^1.2.2
  logger: ^1.1.0
  uuid: ^3.0.6
  random_string: ^2.3.1
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  pdf: ^3.11.1
  path_provider: ^2.1.5
  flutter_email_sender: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    # - assets/icons/
    - assets/vectors/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 800
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/CircularStd-Regular.ttf
          weight: 400